"use client";
import {useActionState,useState} from "react";
import {createStaff,type AccountState} from "@/app/admin/account-actions";
export function CreateStaffForm({ready}:{ready:boolean}){
 const [state,action,pending]=useActionState<AccountState,FormData>(createStaff,{message:""});
 const [name,setName]=useState(state.name??""),[email,setEmail]=useState(state.email??""),[lastResult,setLastResult]=useState(state);
 if(state!==lastResult){setLastResult(state);if(state.success){setName("");setEmail("");}}
 return <form action={action} className="panel staff-create"><h3>Create an officer account</h3><p>Only admins can create officers or assign admin access. Give these credentials privately to the intended officer. No invitation email is sent.</p><fieldset disabled={pending||!ready} className="form-grid"><label className="field">Display name *<input name="name" value={name} onChange={event=>setName(event.target.value)} required maxLength={100}/></label><label className="field">Email *<input name="email" value={email} onChange={event=>setEmail(event.target.value)} type="email" required maxLength={254} autoComplete="off"/></label><label className="field">Initial password (12–72 characters) *<input name="password" type="password" required minLength={12} maxLength={72} autoComplete="new-password"/></label><label className="field">Role<select name="role" defaultValue={state.role??"staff"}><option value="staff">Staff</option><option value="admin">Admin</option></select><span className="muted">Staff request publication approval. Admins review, publish and manage accounts.</span></label></fieldset><button className="button" disabled={pending||!ready}>{pending?"Creating…":"Create officer account"}</button>{state.message&&<p className="form-message" role="status">{state.message}</p>}</form>;
}
