"use client";
import {useActionState,useState} from "react";
import {manageAccount,type AccountState} from "@/app/admin/account-actions";
export function OfficerAccountForm({id,version,name,active,pendingDeletion,canDelete}:{id:string;version:number;name:string;active:boolean;pendingDeletion:boolean;canDelete:boolean}){
 const [state,action,pending]=useActionState<AccountState,FormData>(manageAccount,{message:""});
 const [reason,setReason]=useState(state.reason??""),[confirmation,setConfirmation]=useState(state.confirmation??""),[lastResult,setLastResult]=useState(state);
 if(state!==lastResult){setLastResult(state);if(state.success){setReason("");setConfirmation("");}}
 return <form action={action}><input type="hidden" name="id" value={id}/><input type="hidden" name="version" value={version}/><label className="field">Reason *<input name="reason" value={reason} onChange={event=>setReason(event.target.value)} required maxLength={1000} disabled={pending}/></label><div className="actions">{!pendingDeletion&&<button className="button secondary" name="intent" value={active?"suspend":"activate"} disabled={pending}>{active?"Suspend access":"Restore access"}</button>}</div><details className="delete-account"><summary>{pendingDeletion?"Retry account deletion":"Delete login account"}</summary><p>Permanent deletion removes this officer’s login account. Past notes and decisions stay attributed to them. Type <strong>{name}</strong> to confirm.</p><label className="field">Officer display name<input name="confirmation" value={confirmation} onChange={event=>setConfirmation(event.target.value)} maxLength={100} disabled={pending}/></label><label className="check-field"><input type="checkbox" name="confirm_delete" disabled={pending}/><span>I confirm permanent deletion of this login account.</span></label><button className="button" name="intent" value="delete" disabled={pending||!canDelete}>{pendingDeletion?"Retry deletion":"Delete account"}</button></details>{state.message&&<p className="form-message" role="status">{state.message}</p>}</form>;
}
