import type { Metadata } from "next";
import Link from "next/link";
import { PageIntro } from "@/components/public-content";
import { getPublicConfig } from "@/lib/public-config";
export const metadata: Metadata = { title: "Privacy | Deicidee" };
export default async function Privacy() {
  const { content } = await getPublicConfig();
  return <><PageIntro eyebrow="Your information" title="Recruitment privacy.">Pre-launch notice. Applications are closed; this website is not accepting applicant details.</PageIntro><article className="panel prose"><h2>What the recruitment form will collect</h2><p className="preserve-lines">{content.applicationFields || "The proposed fields are IGN, CrossFire rank, previous clan (including None), Discord contact, Facebook link, reason for joining, and one tryout mode with a relevant map. Whether real names or other fields are required still needs confirmation."}</p><p>The final fields and acknowledgement will be shown before submission. Never provide game passwords, account credentials, or payment details.</p><h2>Purpose and officer access</h2><p>Recruitment information is intended for reviewing applications, arranging tryouts, evaluating attempts, and completing joining steps. Assigned active administrators and staff will have private access. There is no public applicant directory.</p><h2>Live sharing and recordings</h2><p>Live Discord gameplay sharing is separate from storing a recording. This website has no gameplay or voice upload/storage feature. Any future recording request needs its own explanation and agreement.</p><h2>Retention</h2><p className="preserve-lines">{content.retentionPolicy || "The retention and deletion policy is awaiting approval and will be published before applications open. No automatic deletion policy has been assumed."}</p><h2>Corrections and deletion requests</h2><p className="preserve-lines">{content.correctionContact || "The clan's official contact will be published before intake opens. No correction response time is promised."}</p><h2>Website operation</h2><p>The planned hosting providers are Vercel and Supabase. Hosting and security services may process technical request logs. Officer sign-in uses session cookies; no marketing analytics have been added to this website.</p><Link className="text-link" href="/community">Community channels ↗</Link></article></>;
}
